---
- name: Config on R_DC1
  hosts: R_DC1 
  connection: network_cli
  gather_facts: false 
  tasks: 
#Set IP address va cau hinh cho cac port 
    - name: Set IP on interface e0/1 
      ios_config: 
        parents:
          - interface e0/1 
        lines:
          - no shut
          - ip address 192.168.1.9 255.255.255.248
          - ip nat inside
          - ip ospf 1 area 1 
    - name: Set IP on interface e0/2
      ios_config: 
        parents:
          - interface e0/2
        lines:
          - no shut
          - ip address 192.168.1.1 255.255.255.248
          - ip nat inside 
          - ip ospf 1 area 1  
    - name: Set IP on interface e0/3 
      ios_config: 
        parents:
          - interface e0/3
        lines:
          - no shut
          - ip address 10.10.1.2 255.255.255.0
          - ip nat outside
#Khoi tao OSPF Routing 
    - name: Config OSPF with Process ID 1
      ios_config:
        parents:
          - router ospf 1 
        lines:
          - redistribute static subnets
          - default-information originate
#Cau hinh GRE Tunnel
    - name: Config tunnel 
      ios_config:
        parents:
          - interface {{ item.intTunnel}}
        lines:
          - ip address 172.16.{{ item.number }}.2 255.255.255.252
          - tunnel mode gre ip
          - tunnel source 10.10.1.2 
          - tunnel destination 10.10.{{ item.areanum }}.2
      with_items:
        - { intTunnel: Tunnel0, number: 0, areanum: 3}
        - { intTunnel: Tunnel2, number: 2, areanum: 4}   
#Set ACLs, NAT va Static route
    - name: Static route 
      ios_config:
        lines: 
          - access-list 1 permit any
          - ip nat inside source list 1 interface Ethernet0/3 overload
          - ip route 0.0.0.0 0.0.0.0 10.10.1.1
          - ip route 192.168.3.0 255.255.255.0 172.16.0.1 120
          - ip route 192.168.4.0 255.255.255.0 172.16.2.1 120