---
- name: Config on R_DR2
  hosts: R_DR2
  connection: network_cli
  gather_facts: false 
  tasks: 
#Set IP address va cau hinh tren cac port 
    - name: Set IP on interface e0/1 
      ios_config: 
        parents:
          - interface e0/1 
        lines:
          - no shut
          - ip address 192.168.2.17 255.255.255.248
          - ip ospf 1 area 2
    - name: Set IP on interface e0/2
      ios_config: 
        parents:
          - interface e0/2
        lines:
          - no shut
          - ip address 172.16.123.2 255.255.255.0
          - ip ospf 1 area 0
    - name: Set IP on interface e0/3 
      ios_config: 
        parents:
          - interface e0/3
        lines:
          - no shut
          - ip address 192.168.2.2 255.255.255.248
          - ip ospf 1 area 2
#Set OSPF routing
    - name: Config OSPF with Process ID 1
      ios_config:
        lines:
          - router ospf 1 