---
- name: Config on SW_DC 
  hosts: SW_DC 
  connection: network_cli
  gather_facts: false 
  tasks: 
#Set IP address va cau hinh tren cac port
    - name: Set IP on interface e0/1 
      ios_config: 
        parents: 
          - interface e0/1 
        lines:
          - no switchport
          - ip address  192.168.1.254 255.255.255.248 
    - name: Set IP on interface e0/2
      ios_config: 
        parents: 
          - interface e0/2
        lines:
          - no switchport
          - ip address 192.168.1.10 255.255.255.248
          - ip ospf 1 area 1 
    - name: Set IP on interface e0/3
      ios_config: 
        parents: 
          - interface e0/3
        lines:
          - no switchport
          - ip address  192.168.1.18 255.255.255.248
          - ip ospf 1 area 1
    - name: Set IP on interface e1/0
      ios_config: 
        parents: 
          - interface e1/0
        lines:
          - no switchport
          - ip address  192.168.12.1 255.255.255.252
#Set OSPF routing 
    - name: Config OSPF with Process ID 1
      ios_config:
        parents:
          - router ospf 1 
        lines:
          - redistribute connected subnets 